name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install and build in the correct folder
      - run: npm ci
        working-directory: AppV2/vitneboksen

      - run: npm run build
        working-directory: AppV2/vitneboksen

      # Deploy from the correct folder
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VITNEBOKSEN }}
          channelId: live
          projectId: vitneboksen
        # change directory for firebase.json
        env:
          FIREBASE_CLI_PREV_DIR: AppV2/vitneboksen
