name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - run: npm ci
        working-directory: AppV2/vitneboksen

      # Build, with env var passed
      - run: npm run build
        working-directory: AppV2/vitneboksen
        env:
          VIDEO_PROCESSOR_URL: ${{ secrets.VITNEBOKS_API_URL }}

      # Deploy (use CLI directly for subdirectory support)
      - name: Deploy to Firebase Hosting
        run: |
          cd AppV2/vitneboksen
          npx firebase deploy --only hosting --project vitneboksen --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VITNEBOKSEN }}"
