name: Build and deploy ASP.Net Core app to Azure Web App - VinteboksenApiLinux

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_PATH: Api/Vitneboksen_Api  # Relative path to your project
  PUBLISH_PATH: ./published_app       # Explicit publish directory

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build with dotnet
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.PUBLISH_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_33016C231C6F45DE915EFBFA34847574 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5ECD04A3520541EFB0044073A4E7A43D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EFC02380ABD24120A5EC824ABA11A491 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VinteboksenApiLinux'
          slot-name: 'Production'
          package: ${{ env.PUBLISH_PATH }}
